-- INSERT INTO burgers (burger_name, devoured) VALUES ("Squirrel Burger", false);
-- INSERT INTO burgers (burger_name, devoured) VALUES ("Moose Burger", false);
-- INSERT INTO burgers (burger_name, devoured) VALUES ("Opossum Burger", false);
-- INSERT INTO burgers (burger_name, devoured) VALUES ("Armadillo Burger", false);
-- INSERT INTO burgers (burger_name, devoured) VALUES ("Raccoon Burger", false);
